# Generated by Django 3.0.4 on 2020-03-21 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200320_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyPost',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.post',),
        ),
    ]
