# Generated by Django 3.0.4 on 2020-03-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200321_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='projects')),
                ('description', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Ongoing'), (1, 'Completed')], default=0)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
