# Generated by Django 3.0.4 on 2020-03-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='active',
        ),
    ]
